In [4]:
# 全1张量和全0张量
import tensorflow as tf
x = tf.ones(shape=(2,1))
print(x)

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


In [6]:
x = tf.zeros(shape=(2,1))
print(x)

tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [11]:
# 随即张量
import numpy as np
x = tf.random.normal(shape=(3,1),mean=0,stddev=1)  # 均值为0，方差为1
print(x)
# print(np.random.normal(size=(3, 1), loc=0., scale=1.))

tf.Tensor(
[[-0.6512624 ]
 [-0.24783178]
 [-0.06576854]], shape=(3, 1), dtype=float32)
[[-0.51527143]
 [-0.38075276]
 [-1.27040793]]
