In [76]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [77]:
train_images.shape

(60000, 28, 28)

In [78]:
len(train_labels)

60000

In [79]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [80]:
test_images.shape

(10000, 28, 28)

In [81]:
len(test_labels)

10000

In [82]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [83]:
from tensorflow import keras
from keras import layers
model = keras.Sequential([
    layers.Dense(512,activation="relu"),
    layers.Dense(10,activation="softmax")
])

In [84]:
# make exact purpose of the loss function and the optimizer

# the complication step
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [89]:
# before training,reshape the data into the shape the model excepts and scales it
# make sure that all values in the [0,1] interval
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype("float32")/255
test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype("float32")/255

(60000, 784)


In [92]:
# fit the model to its training data
model.fit(train_images,train_labels,epochs=5,batch_size=128)

469/469 [==============================] - 2s 4ms/step - loss: 0.2639 - accuracy: 0.9239
Epoch 4/5
469/469 [==============================] - 2s 4ms/step - loss: 0.2520 - accuracy: 0.9269
Epoch 5/5
469/469 [==============================] - 2s 4ms/step - loss: 0.2401 - accuracy: 0.9305


Epoch 1/5
469/469 [==============================] - 2s 5ms/step - loss: 0.2292 - accuracy: 0.9334
Epoch 2/5
469/469 [==============================] - 2s 5ms/step - loss: 0.2189 - accuracy: 0.9367
Epoch 3/5
469/469 [==============================] - 2s 5ms/step - loss: 0.2093 - accuracy: 0.9395
Epoch 4/5
469/469 [==============================] - 3s 6ms/step - loss: 0.2002 - accuracy: 0.9417
Epoch 5/5
469/469 [==============================] - 3s 6ms/step - loss: 0.1919 - accuracy: 0.9447


In [94]:
# use the model to make predictions
test_digits = test_images[0:10]
predictions  = model.predict(test_digits)
predictions[0]
# each number of index i in that array corresponds to
# the probability that digit image test_digits[0] belongs to class i

1/1 [==============================] - 0s 16ms/step


array([2.2490938e-05, 4.4636521e-09, 3.0119100e-04, 1.9274560e-03,
       1.2065576e-07, 4.6566012e-05, 1.2701981e-10, 9.9731445e-01,
       8.7003273e-06, 3.7902282e-04], dtype=float32)

In [97]:
# highest probability
print(predictions[0].argmax())
# the probability of being a 7
print(predictions[0][7])
# check the test label
print(test_labels[0])

7
0.99731445
7


In [99]:
# compute average accuracy over the entire test set
test_loss,test_acc =model.evaluate(test_images,test_labels)
print(f"test_acc:{test_acc}")
# test_acc is 0.945
# lower than the training-set accuracy
# this gap between training accuracy and test one is overfitting


313/313 [==============================] - 1s 4ms/step - loss: 0.1891 - accuracy: 0.9450
test_acc:0.9449999928474426
