In [15]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [2]:
train_images.shape

(60000, 28, 28)

In [3]:
len(train_labels)

60000

In [4]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
test_images.shape

(10000, 28, 28)

In [6]:
len(test_labels)

10000

In [7]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [8]:
from tensorflow import keras
from keras import layers
model = keras.Sequential([
    layers.Dense(512,activation="relu"),
    layers.Dense(10,activation="softmax")
])

In [9]:
# make exact purpose of the loss function and the optimizer

# the complication step
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [10]:
# before training,reshape the data into the shape the model excepts and scales it
# make sure that all values in the [0,1] interval
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype("float32")/255
test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype("float32")/255

In [11]:
# fit the model to its training data
model.fit(train_images,train_labels,epochs=5,batch_size=128)

Epoch 1/5


2023-03-02 11:24:51.321288: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


469/469 [==============================] - 2s 4ms/step - loss: 0.2640 - accuracy: 0.9230
Epoch 2/5
469/469 [==============================] - 2s 4ms/step - loss: 0.1080 - accuracy: 0.9677
Epoch 3/5
469/469 [==============================] - 2s 3ms/step - loss: 0.0718 - accuracy: 0.9785
Epoch 4/5
469/469 [==============================] - 2s 3ms/step - loss: 0.0518 - accuracy: 0.9844
Epoch 5/5
469/469 [==============================] - 2s 3ms/step - loss: 0.0383 - accuracy: 0.9888


In [12]:
# use the model to make predictions
test_digits = test_images[0:10]
predictions  = model.predict(test_digits)
predictions[0]
# each number of index i in that array corresponds to
# the probability that digit image test_digits[0] belongs to class i

1/1 [==============================] - 0s 46ms/step


array([5.4943985e-08, 2.5694802e-09, 1.4657656e-05, 5.8266251e-05,
       1.0635000e-11, 4.2495887e-09, 4.3571587e-12, 9.9992537e-01,
       2.0352235e-07, 1.2986811e-06], dtype=float32)

In [13]:
# highest probability
print(predictions[0].argmax())
# the probability of being a 7
print(predictions[0][7])
# check the test label
print(test_labels[0])

7
0.9999254
7


In [14]:
# compute average accuracy over the entire test set
test_loss,test_acc =model.evaluate(test_images,test_labels)
print(f"test_acc:{test_acc}")
# test_acc is 0.945
# lower than the training-set accuracy
# this gap between training accuracy and test one is overfitting

313/313 [==============================] - 0s 775us/step - loss: 0.0741 - accuracy: 0.9771
test_acc:0.9771000146865845
