# The gears of neural networks: Tensor operations

In [ ]:
## Element-wise

In [ ]:
def naive_relu(x):
    assert len(x.shape)==2
    x = x.copy()
    for i in range (x.shape[0]):
        for j in range (x.shape[1]):
            x[i,j] = max(x[i,j],0)
    return x

In [ ]:
def naive_add(x,y):
    assert len(x.shape)==2
    assert x.shape == y.shape

    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[i,j]
    return x

## Broadcasting

In [8]:
import numpy as np
X = np.random.random((32,10))
y = np.random.random((10,))

# add an empty first axis to y,whose shape becomes (1,10)
y = np.expand_dims(y,axis=0)
print(y.shape)

(1, 10)


In [4]:
#Then,we repeat y 32 times alongside this new axis,so that we end up
#with a tensor Y with shape(32,10),where Y[i,:] == y for in range(0,32)
Y = np.concatenate([y]*32,axis=0)

In [5]:
# Repeat a vector alongside a new axis 10 times
def naive_add_matrix_and_vector(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] += y[j]
    return x

In [10]:
# element-wise maximum operation of two tensor of different shapes via broadcasting

import numpy as np
x = np.random.random((64,3,32,10))
y = np.random.random((32,10))
z = np.maximum(x,y)
print(z.shape)

(64, 3, 32, 10)


##Tensor product

In [11]:
x = np.random.random((32,))
y = np.random.random((32,))
z = np.dot(x,y)

In [12]:
#Dot product
def naive_vector_dot(x,y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0]==y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z
#Dot product between a matrix x and vector y
#return a vector where the coefficients are the dot products
#between y  and the rows of x
def naive_matrix_vector_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i,j] * y[j]
    return z

In [13]:
# a matrix-vector product and a vector product
def naive_matrix_vector_dot(x,y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i,:],y)
    return z

In [14]:
# dot product between tow matrices
def naive_matrix_dot(x,y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    z = np.zeros((x.shape[0],y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i,:]
            column_y = y[:,j]
            z[i,j] = naive_vector_dot(row_x,column_y)

## Tensor reshaping

In [19]:
# Reshaping a tensor means rearranging its rows and columns to match a
# target shape.
x = np.array([[0.,1.],
              [2.,3.],
              [4.,5.]])
print(x.shape)

x = x.reshape((6,1))
print(x)
print("--------------------")
x= x.reshape((2,3))
print(x)

(3, 2)
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]]
--------------------
[[0. 1. 2.]
 [3. 4. 5.]]


In [20]:
# Transposition
# x[i,:] ---> x[:,i]
x = np.zeros((300,20))
x = np.transpose(x)
print(x.shape)

(20, 300)


##Geometric interpretation of tensor operations
+ Translation
+ Rotation
+ Scaling
+ Linear transform
+ Affine transform