##The engine of neural networks:Gradient-based optimization
`output = relu(dot(input, W) + b)`
W and b are tensors that are attributes of the layer.They're called the weight or trainable parameters of the layer.(kernel and bias)
First,these weight matrices are filled with small random values(random initialization).
Next,gradually adjust these weights,based on a feedback signal.(training)
###training loop
Repeat these steps in a loop, until the loss seems sufficiently low:
+ Draw a batch of training samples, x, and corresponding targets, y_true.
+ Run the model on x (a step called the forward pass) to obtain predictions, y_pred.
+ Compute the loss of the model on the batch, a measure of the mismatch between y_pred and y_true.
+ Update all weights of the model in a way that slightly reduces the loss on this batch.

One naive solution that freeze all weights in the model except the one scalar coefficient being considered is inefficient.We are needed to compute two forward passes.
### Much better approach:gradient descent


In [ ]:
past_velocity = 0
momentum = 0.1 #不变的动量因子
# while loss>0.01:
    

In [5]:
import tensorflow as tf
x = tf.Variable(0.)  # 将标量Variable的值初始化为0
with  tf.GradientTape() as tape: #创建一个GradientTape作用域
    y = 2 * x +3  #在作用域内，对变量进行张量运算
    grad_of_y_wrt_x = tape.gradient(y,x) #利用梯度带获取输出y相对于变量x的梯度

In [7]:
# GradientTape 也可以用于张量运算
x = tf.Variable(tf.zeros(2,2)) # 将Variable初始化为形状（2，2）的零张量
with tf.GradientTape() as tape:
    y = 2 * x + 3
grad_of_y_wrt_x = tape.gradient(y,x) #grad_of_y_wrt_x是一个形状为(2,2)的张量，与x相同
#表示y = 2 * x + 3 在x = [[0,0],[0,0]]附近的曲率


In [11]:
# 适用于变量列表
W = tf.Variable(tf.random.uniform((2,2)))
b = tf.Variable(tf.zeros((2,)))
x = tf.random.uniform((2,2))
with tf.GradientTape() as tape:
    y = tf.matmul(x,W)+b # 在TensorFlow中matmul是指点积
grad_of_y_wrt_W_and_b = tape.gradient(y,[W,b]) #grad_of_y_wrt_W_and_b是由两个张量组成的列表
#这两个张量的形状分别于W和b相同
print(grad_of_y_wrt_W_and_b)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.68255615, 0.68255615],
       [1.2405155 , 1.2405155 ]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>]
